version: '3'

services: 
  redis:
    image: redis:latest
    container_name: "redis_latest"
    restart: always
    ports:
      - 6379:6379
    volumes: 
      - ~/data/redis:/data
    command: redis-server --appendonly yes