version: "3.3"
services:
  jenkins:
    build: ./Dockerfile
    # image: jenkinsci/jenkins:latest
    container_name: tops_jenkins
    user: root
    restart: always
    ports:
      - "9090:8080"
      - "50000:5000"
    volumes:
      - "~/data/jenkins:/var/jenkins_home"
      - "~/data/run/docker-jenkins.sock:/var/run/docker.sock"