- hosts: perf-servers
  vars:
    workspace: /data
  sudo: yes
  tasks:
    - name: ping server
      shell: echo jmeter
    - name: go to workspace
      shell: cd {{workspace}} && echo `pwd` && ls -al && mkdir -p candybox
    
    - name: copy jmeter test plan to folders
      copy:
        src: ../files/candybox/candybox-login.jmx
        dest: "{{workspace}}/candybox/candybox-login.jmx"
    - name: copy run jmeter scripts
      copy:
        src: ../files/candybox/run_jmeter.sh
        dest: "{{ workspace }}/candybox"
    - name: run jmeter scripts
      shell: sh run_jmeter.sh
      args:
        chdir: /data/candybox
      sudo: yes
