- hosts: postgre-server
  become: yes
  task:
    - name: copy install files
      copy:
        src: ../files/install.sh
        dest: /data/postgre
    - name: execute install files
      shell: sh install.sh
      args:
        chdir: /data/postgre
    - name: start postgresql service
      shell: sudo systemctl start postgresql@12-main
