version: "3.3"
services:
  nginx:
    image: nginx
    container_name: tops-nginx
    ports:
      - "80:80"
    volumes:
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./conf/data:/data
    restart: always