version: '3.3'

services:
  db:
    image: mysql:latest
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    container_name: mysql_latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: defi_data 
      MYSQL_USER: defi
      MYSQL_PASSWORD: 123456
      COMMAND: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password #设置utf8字符集
