version: '3.3'

services:
  postgres_db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - /data/sonar-postgre:/var/lib/postgresql
      - /data/sonar-postgre/data:/var/lib/postgresql/data

  sonar_server:
    image: sonarqube
    ports: 
      - "9000:9000"
      - "9092:9092"
    restart: always
    # volumes:
      # - ./sonarqube:/opt/sonarqube
    #   - ./sonar/extensions:/opt/sonarqube/extensions
    #   - ./sonar/docker:/opt/sonarqube/docker
      # - ./sonar/sysctl.conf:/etc/sysctl.conf:ro
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres_db:5432/sonar?charSet=UNICODE
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    links:
      - postgres_db
    # entrypoint: |
    #   bash -c 'bash -s <<EOF
    #   trap "break;exit" SIGHUP SIGINT SIGTERM
    #   sysctl -w vm.max_map_count=262144 && ./bin/run.sh
    #   EOF'