- hosts: goreplay-servers
  vars:
    goreplay_home: /root

  tasks:
    - name: copy goreplay 
      copy:
        src: ../files/goreplay
        dest: "{{goreplay_home}}"
      tags:
        - install_goreplay

    - name: chmod in goreplay
      shell: chmod +x goreplay
      tags:
        - install_goreplay
